//! Applies the Pest tokenisation grammar and represents data from the resulting matches.
//!
//! See tokenise.pest in this directory for the grammar itself.

use crate::Edition;
use crate::reimplementation::pegs::{
    MatchData, ParticipationOutcome, attempt_for_participating_matches,
};

/// Attempts to match the specified edition's tokens nonterminal.
///
/// Reports an error message if it finds a problem in the reimplementation's model (in particular,
/// if the match attempt fails).
pub fn match_tokens(edition: Edition, input: &[char]) -> Result<TokensMatchData, String> {
    let tokens_nonterminal = tokens_nonterminal_for_edition(edition);
    let s: String = input.iter().collect();
    let ParticipationOutcome::Success {
        participating_matches,
        consumed_entire_input,
    } = attempt_for_participating_matches::<Nonterminal, TokenParser>(
        tokens_nonterminal,
        &s,
        is_tokenisation_nonterminal,
    )?
    else {
        // This shouldn't fail, because the tokens nonterminal's expression is a zero-or-more
        // repetitions operator.
        return Err(format!("{tokens_nonterminal:?} match attempt failed"));
    };
    Ok(TokensMatchData {
        tokenisation_matches: participating_matches,
        consumed_entire_input,
    })
}

/// Information about an attempt to match an edition's tokens nonterminal.
///
/// The tokens nonterminal's expression is a zero-or-more repetitions expression, so the match
/// attempt is always successful.
pub struct TokensMatchData {
    /// The participating matches of tokenisation nonterminals
    pub tokenisation_matches: Vec<TokenisationMatch>,
    /// Whether the match attempt consumed the complete input
    pub consumed_entire_input: bool,
}

/// Returns the tokens nonterminal for the specified Rust edition.
fn tokens_nonterminal_for_edition(edition: Edition) -> Nonterminal {
    match edition {
        Edition::E2015 => Nonterminal::TOKENS_2015,
        Edition::E2021 => Nonterminal::TOKENS_2021,
        Edition::E2024 => Nonterminal::TOKENS_2024,
    }
}

/// Whether a nonterminal from the tokenisation grammar is a tokenisation nonterminal.
fn is_tokenisation_nonterminal(nonterminal: Nonterminal) -> bool {
    is_token_nonterminal(nonterminal) || is_reserved_form_nonterminal(nonterminal)
}

/// Whether a nonterminal from the tokenisation grammar is a token nonterminal.
fn is_token_nonterminal(nonterminal: Nonterminal) -> bool {
    matches!(
        nonterminal,
        Nonterminal::Whitespace
            | Nonterminal::Line_comment
            | Nonterminal::Block_comment
            | Nonterminal::Character_literal
            | Nonterminal::Byte_literal
            | Nonterminal::String_literal
            | Nonterminal::Byte_string_literal
            | Nonterminal::C_string_literal
            | Nonterminal::Raw_string_literal
            | Nonterminal::Raw_byte_string_literal
            | Nonterminal::Raw_c_string_literal
            | Nonterminal::Float_literal
            | Nonterminal::Integer_literal
            | Nonterminal::Raw_lifetime_or_label
            | Nonterminal::Lifetime_or_label
            | Nonterminal::Raw_ident
            | Nonterminal::Ident
            | Nonterminal::Punctuation
    )
}

/// Whether a nonterminal from the tokenisation grammar is a reserved-form nonterminal.
fn is_reserved_form_nonterminal(nonterminal: Nonterminal) -> bool {
    matches!(
        nonterminal,
        Nonterminal::Reserved_block_comment_start
            | Nonterminal::Reserved_literal_2015
            | Nonterminal::Reserved_literal_2021
            | Nonterminal::Reserved_single_quoted_literal_2015
            | Nonterminal::Reserved_single_quoted_literal_2021
            | Nonterminal::Reserved_guard
            | Nonterminal::Reserved_float
            | Nonterminal::Reserved_lifetime_or_label_prefix
            | Nonterminal::Reserved_prefix_2015
            | Nonterminal::Reserved_prefix_2021
    )
}

#[derive(pest_derive::Parser)]
#[grammar = "reimplementation/tokenisation/tokenise.pest"]
/// Parser for the tokenisation grammar, generated by Pest.
struct TokenParser;

/// Enumeration of the nonterminals used in the tokenisation grammar.
///
/// This includes:
/// - the tokens nonterminals       (named like TOKENS_yyyy)
/// - the tokenisation nonterminals (named in Title_case)
/// - subsidiary nonterminals       (named in UPPER_CASE)
///
/// The nonterminals which are documented as terminals don't appear here, because they are defined
/// using Pest silent rules.
pub type Nonterminal = Rule;

/// Information from a successful match attempt of a tokenisation nonterminal.
///
/// As far as the type system is concerned this could be a match of any nonterminal from the
/// tokenisation grammar, but we only use it for tokenisation nonterminals.
pub type TokenisationMatch = MatchData<Nonterminal>;
