//! Strings for testing lexing.
#![cfg_attr(rustfmt, rustfmt_skip)]

/// The list of test strings used with the --short CLI option.
pub const SHORTLIST: &[&str] = [
    "/* my source file */ fn main() { println!(\"zebra\"); }\n",
    "🦀c",
].as_slice();

/// The list of test strings used by default.
pub const LONGLIST: &[&str] = [

    //// Whitespace

    "",
    " ",
    "  ",
    "\n",
    "\r",
    "\t",
    " \n\r\t ",
    "\u{000B} \u{000C} \u{0085} \u{200E} \u{200F} \u{2028} \u{2029}",


    //// Comments

    "/noncomment",
    "//comment",
    "//comment\n",
    "//comment\n ",
    "//comment\nnext",
    "/// doc comment",
    "/// doc comment\nnext",
    "//// not a doc comment",
    "//// not a doc comment\nnext",
    "//! inner doc comment",
    "//! inner doc comment\nnext",
    "/",
    "//",
    "///",
    "//!",
    "//\nx",
    "///\nx",
    "//!\nx",
    "//!!",
    "/// this is not NFC qa\u{0301}",

    "/* comment */",
    "/* comment */+",
    "/** doc comment */",
    "/** doc comment */+",
    "/*** not a doc comment */+",
    "/*! inner doc comment */+",
    "/*",
    "/**",
    "/* unterminated",
    "/* unterminated*",
    "/* unterminated/",
    "xxx /* yyy",
    "/*/+",
    "/**/+",
    "/***/+",
    "/*!*/",
    "/*!!*/",
    "/*/*/+",
    "/*/**/*/+",
    "/* xxx /*/+",
    "/* /* xxx */ */+",
    "/*//* /** ///** xxx */*/*/*/+",
    "/* /* xxx */*/+",
    "/* /*/*/* xxx */**/*// */+",
    "/* /* /* /* xxx */ yyy /* */ */ */ */+",

    "// CR \r in line comment",
    "/// CR \r in line doc comment",
    "//! CR \r in inner line doc comment",
    "/* CR \r in block comment */",
    "/** CR \r in block doc comment */",
    "/*! CR \r in inner block doc comment */",

    "//\r CR starting line comment",
    "///\r CR starting line doc comment",
    "//!\r CR starting inner line doc comment",
    "/*\r CR starting block comment */",
    "/**\r CR starting block doc comment */",
    "/*!\r CR starting inner block doc comment */",

    r##"/// doc-comment with " in it"##,
    r##"/// doc-comment with "# in it"##,
    r##"/** doc-comment with " in it*/"##,
    r##"/** doc-comment with "# in it*/"##,
    // 254 hashes
    "/** \"############################################################################################################################################################################################################################################################## */",
    // 255 hashes
    "/** \"############################################################################################################################################################################################################################################################### */",

    " //comment",
    " /* comment */ ",
    " /** doc comment */ ",


    //// Punctuation

    "! # $ % & ( ) * + , - . / : ; < = > ? @ [ ] ^ _ { | } ~",
    "!#$%&()*+,-./:;<=>?@[]^_{|}~",
    r"\",
    "`",

    "++",
    "--",
    "&&",
    "&&+",
    "&& +",
    "& &",
    ">>",
    ">>=",
    ">> =",
    "> >=",
    ">>>",

    "..",
    "...",
    "....",
    ".....",

    "==",
    "===",

    ".=",
    "..=",
    "...=",
    "..==",

    "<<<<",
    "<=<=",
    "<<=",
    "<<<=",
    "<<==",

    "=>=>",
    ">=>=",
    ">>>=",
    ">>==",

    "||",
    "|||",
    "||||",

    "::",
    "!=",
    "->",
    "<-",
    "+=",
    "-=",
    "*=",
    "/=",
    "%=",
    "^=",
    "&=",
    "|=",

    "$=",
    ":=",
    ";=",
    "?=",
    "@=",
    "~=",

    "##",
    "###",
    "####",
    "#####",

    "x ➖ y",


    //// Identifiers and keywords

    "x",
    "b",
    "c",
    "r",
    "xxx",
    "for",
    "_",
    "__",
    "x_",
    "_x",
    "__x__",
    "Москва",
    "東京",
    "€",
    "$crate",
    "r#",
    "r# ",
    "r#x",
    "r#xxx",
    "r#東京",
    "r#for",
    "r#_for",
    "r#3",
    "r#_",
    "r#__",
    "r#crate",
    "r#self",
    "r#super",
    "r#Self",

    "🦁",
    "a🦁",
    "🦁b",
    "🦀c",

    // Identifiers that do and don't need NFC normalisation
    "qa\u{0301}",
    "q\u{e1}",
    "r#qa\u{0301}",
    "r#q\u{e1}",
    "Kelvin Kelvin",
    "Ⅹ Ⅰ Ⅽ",

    // Example of a new character in Unicode 16.0
    "\u{105C9}",
    // Decomposed form of U+105C9
    "\u{105D2}\u{0307}",

    //// Reserved prefixes

    "k#a",
    "q#a",
    "_#a",
    "b#a",
    "c#a",
    "k#'",
    "q#'",
    "_#'",
    "b#'",
    "c#'",

    "br#",
    "br# ",
    "br#x",
    "cr#",
    "cr# ",
    "cr#x",
    "qr#",
    "qr# ",
    "qr#x",

    // See https://github.com/rust-lang/rust/issues/123696
    // (Fixed in rustc 1.79)
    "🦁#",

    //// Double-quote forms

    r#"""#,
    r#""""#,
    r#"""""#,
    r#" " "#,
    r#" "" "#,
    r#" """ "#,

    r#" ""suff"#,
    r#" ""a_"#,
    r#" ""_a"#,
    r#" ""__"#,
    r#" ""_"#,

    "\"xxx\"",
    "\"x\ny\"",
    "\"x\n\ny\"",
    "\"x\ty\"",

    r#" xxx""#,
    r#" "yyy"#,
    r#" xxx"yyy"#,
    r#" xxx"yyy\""#,
    r#" xxx"yyy\"""#,
    r#" xxx"""#,
    r#" "xxx"yyy""#,
    r#" "xxx"""#,
    r#" "xxx""""#,
    r#" "xxx"r"""#,
    r#" "xxx"yyy"zzz"#,
    r#" "xxx"yyy"zzz""#,
    r#" xxx\"yyy"#,

    r#" xxr""#,
    r#" xxr"yyy"#,
    r#" xxr"yyy\""#,
    r#" xxr"yyy\"""#,
    r#" xxr"""#,
    r#" xxr\"yyy"#,
    r#" for""#,
    r#" for"yyy"#,
    r#" for"yyy\""#,
    r#" for"yyy\"""#,
    r#" for"""#,
    r#" for\"yyy"#,

    r#" "xxx"r""#,
    r#" "xxx"r"zzz"#,
    r#" "xxx"r"zzz""#,
    r#" "xxx"b""#,
    r#" "xxx"b"zzz"#,
    r#" "xxx"b"zzz""#,
    r#" r"xxx"""#,
    r#" r"xxx"r""#,
    r#" r"xxx"r"""#,
    r#" r"xxx"r"zzz"#,
    r#" r"xxx"r"zzz""#,
    r#" r"xxx"r"zzz\""#,
    r#" r"xxx"r"zzz\"""#,
    r#" r"xxx"b""#,
    r#" r"xxx"b"zzz"#,
    r#" r"xxx"b"zzz""#,

    r#" b""#,
    r#" b"yyy"#,
    r#" b"yyy""#,

    r#" r""#,
    r#" r"yyy"#,
    r#" r"yyy""#,
    "r\"x\ny\"",
    "r\"x\n\ny\"",

    r#" br""#,
    r#" br"yyy"#,
    r#" br"yyy""#,
    "br\"x\ny\"",
    "br\"x\n\ny\"",

    r#" c""#,
    r#" c"yyy"#,
    r#" c"yyy""#,
    "c\"x\ny\"",
    "c\"x\n\ny\"",

    r#" cr""#,
    r#" cr"yyy"#,
    r#" cr"yyy""#,
    "cr\"x\ny\"",
    "cr\"x\n\ny\"",

    r#" _""#,
    r#" _"yyy"#,
    r#" _"yyy""#,


    //// Raw-string forms

    r#" r"" "#,
    r#" r"xxx" "#,
    r#" r"\" "#,
    r#" r"\\" "#,
    r#" r"\u{00E6}" "#,

    r##" r#""# "##,
    r##" r#"""# "##,
    r##" r#"x"yy"# "##,
    r##" r#"unterminated" "##,
    r##" r#"xxx#yyy"# "##,
    r##" r#~"x"# "##,

    r###" r##""## "###,
    r###" r##"""## "###,
    r###" r##"x"yy"## "###,
    r###" r##"unterminated" "###,
    r###" r##"unterminated"# "###,
    r###" r##"xxx#yyy"## "###,
    r###" r##"xxx##yyy"## "###,
    r###" r##"xxx"#yyy"## "###,

    r###" r#"extra"## "###,
    r###" r#"extra"##n "###,
    r####" r###"xxx"### "####,
    r####" r#"extra"### "####,
    r####" r##"extra"### "####,

    r##" r""suff "##,
    r##" r"xxx"suff "##,
    r##" r#"xxx"#suff "##,
    r###" r##"xxx"##suff "###,

    r##" qr#""# "##,
    r##" qr#"""# "##,
    r##" qr#"x"yy"# "##,
    r##" qr#"unterminated" "##,
    r##" qr#"xxx#yyy"# "##,

    r##" r"xxx"_a "##,
    r##" r"xxx"__ "##,
    r##" r"xxx"_ "##,
    r##" r"xxx"_" "##,
    r##" r#"xxx"#_a "##,
    r##" r#"xxx"#__ "##,
    r##" r#"xxx"#_ "##,

    " r###############################################################################################################################################################################################################################################################\"aaa\"############################################################################################################################################################################################################################################################### ",
    " r################################################################################################################################################################################################################################################################\"aaa\"################################################################################################################################################################################################################################################################ ",
    " br###############################################################################################################################################################################################################################################################\"aaa\"############################################################################################################################################################################################################################################################### ",
    " br################################################################################################################################################################################################################################################################\"aaa\"################################################################################################################################################################################################################################################################ ",
    " cr###############################################################################################################################################################################################################################################################\"aaa\"############################################################################################################################################################################################################################################################### ",
    " cr################################################################################################################################################################################################################################################################\"aaa\"################################################################################################################################################################################################################################################################ ",

    r#" br"" "#,
    r#" br"yyy" "#,
    r#" br"\" "#,

    r##" br#""# "##,
    r##" br#"""# "##,
    r##" br#"x"yy"# "##,
    r##" br#"unterminated" "##,
    r##" br#"xxx#yyy"# "##,
    r##" br#~"x"# "##,

    r###" br##""## "###,
    r###" br##"""## "###,
    r###" br##"x"yy"## "###,
    r###" br##"unterminated" "###,
    r###" br##"unterminated"# "###,
    r###" br##"xxx#yyy"## "###,
    r###" br##"xxx##yyy"## "###,
    r###" br##"xxx"#yyy"## "###,

    r#" cr"" "#,
    r#" cr"yyy" "#,
    r#" cr"\" "#,

    r##" cr#""# "##,
    r##" cr#"""# "##,
    r##" cr#"x"yy"# "##,
    r##" cr#"unterminated" "##,
    r##" cr#"xxx#yyy"# "##,
    r##" cr#~"x"# "##,

    r###" cr##""## "###,
    r###" cr##"""## "###,
    r###" cr##"x"yy"## "###,
    r###" cr##"unterminated" "###,
    r###" cr##"unterminated"# "###,
    r###" cr##"xxx#yyy"## "###,
    r###" cr##"xxx##yyy"## "###,
    r###" cr##"xxx"#yyy"## "###,


    //// Single-quote forms (both character literals and lifetimes/labels)

    " '",
    " ''",
    " '''",
    " 'x",
    " ' x",
    " 'x'",
    " 'x''",
    " 'x'y",
    " 'x'yyy",
    " 'x'y'",
    " 'x'yyy'",
    " 'x'y y'",
    " 'x'y'z",
    " 'x'yyy'z",
    " 'x'y y'z",
    " 'x'_",
    " 'x'__",
    " 'x+'y ",
    " 'x#'y ",
    r#" 'x""'y "#,
    r#" 'y"'" "#,
    " 'xxx",
    " 'xxx'",
    " 'xxx'y",
    " 'xxx'yyy",
    " 'xxx'y'",
    " 'xxx'yyy'",
    " 'xxx'y y'",
    " 'xxx'y'z",
    " 'xxx'yyy'z",
    " 'xxx'y y'z",
    " '.",
    " '.'",
    " '..'",
    " '.'y",
    " '..'y",
    " '_",
    " '#",
    " '##",
    " '#x",
    " '#x'y",
    " 'r#",
    " 'x#",
    " 'xx#",
    " 'r#x",
    " 'x#x",
    " 'xx#x",
    " '$#x",
    " '£#x",
    " 'r#x'y",
    " 'r#xx'y",
    " 'r#xx#'y'",
    " 'r#'",
    " 'r#'b",
    " r#xx'",
    " r#xx'y",
    " 'x'r#y",
    " 'xx'r#y",
    " x'",
    " x''",
    " x'''",
    " x'y",
    " x'yyy",
    " x'y'",
    " x'yyy'",
    " x'y y'",
    " x'y''",
    " x'yyy''",
    " x'y y''",
    " x'y'z",
    " x'yyy'z",
    " x'y y'z",
    " x'y'z'",
    " x'yyy'z'",
    " x'y y'z'",
    " xxx'",
    " xxx''",
    " xxx'''",
    " xxx'y",
    " xxx'yyy",
    " xxx'y'",
    " xxx'yyy'",
    " xxx'y y'",
    " xxx'y''",
    " xxx'yyy''",
    " xxx'y y''",
    " xxx'y'z",
    " xxx'yyy'z",
    " xxx'y y'z",
    " xxx'y'z'",
    " xxx'yyy'z'",
    " xxx'y y'z'",
    " b'",
    " b''",
    " b'''",
    " b'y",
    " b'yyy",
    " b'y'",
    " b'yyy'",
    " b'y y'",
    " b'y''",
    " b'yyy''",
    " b'y y''",
    " b'y'z",
    " b'y'_",
    " b'yyy'z",
    " b'y y'z",
    " b'y'z'",
    " b'yyy'z'",
    " b'y y'z'",
    " 'b'c'd",
    " _'",
    " _''",
    " _'''",
    " _'y",
    " _'yyy",
    " _'y'",
    " _'yyy'",
    " _'y y'",
    " _'y''",
    " _'yyy''",
    " _'y y''",
    " _'y'z",
    " _'yyy'z",
    " _'y y'z",
    " _'y'z'",
    " _'yyy'z'",
    " _'y y'z'",

    "'_",
    "'__",
    "'for",
    "'crate",
    "'self",
    "'super",
    "'Self",
    "'r#_",
    "'r#__",
    "'r#crate",
    "'r#self",
    "'r#super",
    "'r#Self",

    r#" 'x"a" "#,
    r#" 'r"a" "#,
    r#" 'b"a" "#,
    r#" 'b"€" "#,
    r#" 'c"\0" "#,

    //// Forms related to the "Guarded string literals" 2024 reservations
    " #\"xxx\"# ",
    " ##\"xxx\"## ",
    " ###\"xxx\"### ",
    " ####\"xxx\"#### ",
    " #####\"xxx\"##### ",
    " #\"xxx\" ",
    " ##\"xxx\"# ",
    " #\"xxx",
    " #\"\"# ",
    " ##\"\"## ",
    " #\"\" ",
    " ##\"\"# ",
    " #\"",
    " ###############################################################################################################################################################################################################################################################\"aaa\"############################################################################################################################################################################################################################################################### ",
    " ################################################################################################################################################################################################################################################################\"aaa\"################################################################################################################################################################################################################################################################ ",
    "£#\"\"#",
    "#'xxx'#",
    "#''#",


    //// Lifetime/label non-ascii
    "'a🦁",
    "'a\u{0301}",
    "'\u{e1}",
    "'Kelvin 'Kelvin",
    "'r#Kelvin 'r#Kelvin",

    //// String escaping (before processing)

    r#" "\""#,
    r#" "\\""#,
    r#" "\\\""#,
    r#" "\\\\""#,
    r#" "\\"suff "#,
    r#" "\"""#,
    r#" "\\"""#,

    r#" b"\""#,
    r#" b"\\""#,
    r#" b"\\\""#,
    r#" b"\\\\""#,
    r#" b"\\"suff "#,
    r#" b"\"""#,
    r#" b"\\"""#,
    r#" b"xy"_ "#,

    r#" c"\""#,
    r#" c"\\""#,
    r#" c"\\\""#,
    r#" c"\\\\""#,
    r#" c"\\"suff "#,
    r#" c"\"""#,
    r#" c"\\"""#,
    r#" c"xy"_ "#,

    " \"x \n \0 z\" ",
    " b\"x \n \0 z\" ",
    " c\"x \n z\" ",
    " r\"x \n \0 z\" ",
    " br\"x \n \0 z\" ",
    " cr\"x \n z\" ",

    " \"£ á Ω 🦀 \x07 \u{FFFF} \" ",
    " b\"\x07 \" ",
    " b\"\t \" ",
    " b\"\u{007F} \" ",
    " b\"\u{0080} \" ",
    " b\"£ \" ",
    " br\"\u{007F} \" ",
    " br\"\u{0080} \" ",
    " br\"£ \" ",
    " cr\"\u{007F} \" ",
    " cr\"\u{0080} \" ",
    " cr\"£ \" ",
    " c\"£ á Ω 🦀 \x07 \t \u{FFFF} \" ",
    " r\"£ á Ω 🦀 \x07 \t \u{FFFF} \" ",
    " br\"£ á Ω 🦀 \x07 \t \u{FFFF} \" ",
    " cr\"£ á Ω 🦀 \x07 \t \u{FFFF} \" ",

    r" '\'",
    r" '\\'",
    r" '\\\'",
    r" '\\\\'",
    r" '\\'suff ",
    r" '\''",
    r" '\\''",

    r" '£' ",
    r" '🦀' ",
    r" '\nx' ",
    r" '\u{00e6}x' ",
    " '\\\n' ",
    " '\\\n ' ",
    " '\x00' ",
    " '\t' ",
    " '\n' ",
    r#" '"' "#,
    " '\x07' ",
    " '\u{007F}' ",
    " '\u{0080}' ",
    " '\u{FFFF}' ",

    r" b'£' ",
    r" b'🦀' ",
    r" b'\nx' ",
    r" b'\u{00e6}x' ",
    r" b'\' ",
    r" b'\\' ",
    " b'\\\n' ",
    " b'\\\n ' ",
    " b'\x00' ",
    " b'\t' ",
    " b'\n' ",
    r#" b'"' "#,
    " b'\x07' ",
    " b'\u{007F}' ",
    " b'\u{0080}' ",
    " b'\u{FFFF}' ",

    // String unescaping

    r#" "\x00 \x79 \x7a \x7f \' \" \n \r \t \\ \0" "#,
    r#" "\x00\x7f\'\"\n\r\t\\\0" "#,
    r#" "\x80" "#,
    r#" "\xff" "#,
    r#" "\x" "#,
    r#" "\xz" "#,
    r#" "\xzz" "#,
    r#" "\x\\" "#,
    r#" "\z" "#,

    r#" "\u{0}" "#,
    r#" "\u{0000}" "#,
    r#" "\u{000000}" "#,
    r#" "\u{00e6}" "#,
    r#" "\u{00E6}" "#,
    r#" "\u{2192}" "#,
    r#" "\u{1f980}" "#,
    r#" "abc\u{00E6}" "#,
    r#" "\u{00E6}\n" "#,
    r#" "\u{00E6" "#,
    r#" "\u{00E6abc" "#,
    r#" "\u{00E6\n" "#,
    r#" "\u00E6}" "#,
    r#" "\u00E6" "#,
    r#" "\u{00}" "#,
    r#" "\u{ff}" "#,
    r#" "\u{00_00_E6}" "#,
    r#" "\u{00__00E6}" "#,
    r#" "\u{00___00E6}" "#,
    r#" "\u{00 00E6}" "#,
    r#" "\u{00-00E6}" "#,
    r#" "\u{00000E6}" "#,
    r#" "\u{10FFFF}" "#,
    r#" "\u{110000}" "#,
    r#" "\u{00a6}" "#,
    r#" "\u{00A6}" "#,
    r#" "\u{00g6}" "#,
    r#" "\u{00G6}" "#,
    r#" "\u{D7FF}" "#,
    r#" "\u{D800}" "#,
    r#" "\u{DFFF}" "#,
    r#" "\u{E000}" "#,
    r#" "\u{1}" "#,
    r#" "\u{-1}" "#,
    r#" "\u{}" "#,
    r#" "\u{_}" "#,
    r#" "\u{_00e6}" "#,
    r#" "\u{00e6_}" "#,
    r#" "\u{00e6__}" "#,
    r#" "\u00e6" "#,

    r#" b"\x00 \x7f \' \" \n \r \t \\ \0" "#,
    r#" b"\x80 \xff \x90 \xA0" "#,
    r#" b"\xfg" "#,
    r#" b"\u{007F}" "#,
    r#" b"\u{0080}" "#,
    r#" b"\u{00e6}" "#,
    r#" b"\u{110000}" "#,
    r#" b"\u{d800}" "#,
    r#" b"\z" "#,

    r#" c"\x7f \' \" \n \r \t \\" "#,
    r#" c"\x80 \xff" "#,
    r#" c"\u{007f}" "#,
    r#" c"\u{0080}" "#,
    r#" c"\u{00e6}" "#,
    r#" c"\u{2192}" "#,
    r#" c"\u{1f980}" "#,
    r#" c"\u{110000}" "#,
    r#" c"\u{d800}" "#,
    r#" c"\z" "#,
    " c\"\u{007F}\" ",
    " c\"\u{0080}\" ",
    r#" c"£" "#,

    r" '\x00' ",
    r" '\x7f' ",
    r" '\x80' ",
    r" '\x79' ",
    r" '\x7A' ",
    r" '\xff' ",
    r" '\u{00e6}' ",
    r" '\u{2192}' ",
    r" '\u{110000}' ",
    r" '\u{d800}' ",
    r" ' ' ",
    r" '\n' ",
    r" '\r' ",
    r" '\t' ",
    r" '\0' ",
    r#" '\"' "#,

    r" b'\x00' ",
    r" b'\x7f' ",
    r" b'\x80' ",
    r" b'\x79' ",
    r" b'\x7A' ",
    r" b'\xff' ",
    r" b'\u{007F}' ",
    r" b'\u{0080}' ",
    r" b'\u{00e6}' ",
    r" b'\u{2192}' ",
    r" b'\u{110000}' ",
    r" b'\u{d800}' ",
    r" b' ' ",
    r" b'\n' ",
    r" b'\r' ",
    r" b'\t' ",
    r" b'\0' ",
    r#" b'\"' "#,

    " \"string\\\ncontinuation\"",
    " \"string\\\n continuation\"",
    " \"string\\\n\n\r\tcontinuation\"",
    " \"string\\\n    ",

    " b\"string\\\ncontinuation\"",
    " b\"string\\\n continuation\"",
    " b\"string\\\n\n\r\tcontinuation\"",
    " b\"string\\\n    ",

    " c\"string\\\ncontinuation\"",
    " c\"string\\\n continuation\"",
    " c\"string\\\n\n\r\tcontinuation\"",
    " c\"string\\\n    ",

    // PATTERN_WHITESPACE that isn't in CONTINUATION_WHITESPACE isn't eaten
    " \"string\\\n\u{000B}continuation\"",
    " \"string\\\n\u{000C}continuation\"",
    " \"string\\\n\u{0085}continuation\"",
    " \"string\\\n\u{200E}continuation\"",
    " \"string\\\n\u{200F}continuation\"",
    " \"string\\\n\u{2028}continuation\"",
    " \"string\\\n\u{2029}continuation\"",

    " \"non-NFC a\u{0301}\" ",
    " \"NFC \u{e1}\" ",
    " \"Kelvin Kelvin\" ",


    //// Single-character backslash forms that aren't simple escapes

    r" '\ ' ",
    r" '\!' ",
    r" '\#' ",
    r" '\$' ",
    r" '\%' ",
    r" '\&' ",
    r" '\(' ",
    r" '\)' ",
    r" '\*' ",
    r" '\+' ",
    r" '\,' ",
    r" '\-' ",
    r" '\.' ",
    r" '\/' ",
    r" '\1' ",
    r" '\2' ",
    r" '\3' ",
    r" '\4' ",
    r" '\5' ",
    r" '\6' ",
    r" '\7' ",
    r" '\8' ",
    r" '\9' ",
    r" '\:' ",
    r" '\;' ",
    r" '\<' ",
    r" '\=' ",
    r" '\>' ",
    r" '\?' ",
    r" '\@' ",
    r" '\A' ",
    r" '\B' ",
    r" '\C' ",
    r" '\D' ",
    r" '\E' ",
    r" '\F' ",
    r" '\G' ",
    r" '\H' ",
    r" '\I' ",
    r" '\J' ",
    r" '\K' ",
    r" '\L' ",
    r" '\M' ",
    r" '\N' ",
    r" '\O' ",
    r" '\P' ",
    r" '\Q' ",
    r" '\R' ",
    r" '\S' ",
    r" '\T' ",
    r" '\U' ",
    r" '\V' ",
    r" '\W' ",
    r" '\X' ",
    r" '\Y' ",
    r" '\Z' ",
    r" '\[' ",
    r" '\]' ",
    r" '\^' ",
    r" '\_' ",
    r" '\`' ",
    r" '\a' ",
    r" '\b' ",
    r" '\c' ",
    r" '\d' ",
    r" '\e' ",
    r" '\f' ",
    r" '\g' ",
    r" '\h' ",
    r" '\i' ",
    r" '\j' ",
    r" '\k' ",
    r" '\l' ",
    r" '\m' ",
    r" '\o' ",
    r" '\p' ",
    r" '\q' ",
    r" '\s' ",
    r" '\u' ",
    r" '\v' ",
    r" '\w' ",
    r" '\x' ",
    r" '\y' ",
    r" '\z' ",
    r" '\{' ",
    r" '\|' ",
    r" '\}' ",
    r" '\~' ",

    r#" "\ " "#,
    r#" "\!" "#,
    r#" "\#" "#,
    r#" "\$" "#,
    r#" "\%" "#,
    r#" "\&" "#,
    r#" "\(" "#,
    r#" "\)" "#,
    r#" "\*" "#,
    r#" "\+" "#,
    r#" "\," "#,
    r#" "\-" "#,
    r#" "\." "#,
    r#" "\/" "#,
    r#" "\1" "#,
    r#" "\2" "#,
    r#" "\3" "#,
    r#" "\4" "#,
    r#" "\5" "#,
    r#" "\6" "#,
    r#" "\7" "#,
    r#" "\8" "#,
    r#" "\9" "#,
    r#" "\:" "#,
    r#" "\;" "#,
    r#" "\<" "#,
    r#" "\=" "#,
    r#" "\>" "#,
    r#" "\?" "#,
    r#" "\@" "#,
    r#" "\A" "#,
    r#" "\B" "#,
    r#" "\C" "#,
    r#" "\D" "#,
    r#" "\E" "#,
    r#" "\F" "#,
    r#" "\G" "#,
    r#" "\H" "#,
    r#" "\I" "#,
    r#" "\J" "#,
    r#" "\K" "#,
    r#" "\L" "#,
    r#" "\M" "#,
    r#" "\N" "#,
    r#" "\O" "#,
    r#" "\P" "#,
    r#" "\Q" "#,
    r#" "\R" "#,
    r#" "\S" "#,
    r#" "\T" "#,
    r#" "\U" "#,
    r#" "\V" "#,
    r#" "\W" "#,
    r#" "\X" "#,
    r#" "\Y" "#,
    r#" "\Z" "#,
    r#" "\[" "#,
    r#" "\]" "#,
    r#" "\^" "#,
    r#" "\_" "#,
    r#" "\`" "#,
    r#" "\a" "#,
    r#" "\b" "#,
    r#" "\c" "#,
    r#" "\d" "#,
    r#" "\e" "#,
    r#" "\f" "#,
    r#" "\g" "#,
    r#" "\h" "#,
    r#" "\i" "#,
    r#" "\j" "#,
    r#" "\k" "#,
    r#" "\l" "#,
    r#" "\m" "#,
    r#" "\o" "#,
    r#" "\p" "#,
    r#" "\q" "#,
    r#" "\s" "#,
    r#" "\u" "#,
    r#" "\v" "#,
    r#" "\w" "#,
    r#" "\x" "#,
    r#" "\y" "#,
    r#" "\z" "#,
    r#" "\{" "#,
    r#" "\|" "#,
    r#" "\}" "#,
    r#" "\~" "#,

    r#" b"\ " "#,
    r#" b"\!" "#,
    r#" b"\#" "#,
    r#" b"\$" "#,
    r#" b"\%" "#,
    r#" b"\&" "#,
    r#" b"\(" "#,
    r#" b"\)" "#,
    r#" b"\*" "#,
    r#" b"\+" "#,
    r#" b"\," "#,
    r#" b"\-" "#,
    r#" b"\." "#,
    r#" b"\/" "#,
    r#" b"\1" "#,
    r#" b"\2" "#,
    r#" b"\3" "#,
    r#" b"\4" "#,
    r#" b"\5" "#,
    r#" b"\6" "#,
    r#" b"\7" "#,
    r#" b"\8" "#,
    r#" b"\9" "#,
    r#" b"\:" "#,
    r#" b"\;" "#,
    r#" b"\<" "#,
    r#" b"\=" "#,
    r#" b"\>" "#,
    r#" b"\?" "#,
    r#" b"\@" "#,
    r#" b"\A" "#,
    r#" b"\B" "#,
    r#" b"\C" "#,
    r#" b"\D" "#,
    r#" b"\E" "#,
    r#" b"\F" "#,
    r#" b"\G" "#,
    r#" b"\H" "#,
    r#" b"\I" "#,
    r#" b"\J" "#,
    r#" b"\K" "#,
    r#" b"\L" "#,
    r#" b"\M" "#,
    r#" b"\N" "#,
    r#" b"\O" "#,
    r#" b"\P" "#,
    r#" b"\Q" "#,
    r#" b"\R" "#,
    r#" b"\S" "#,
    r#" b"\T" "#,
    r#" b"\U" "#,
    r#" b"\V" "#,
    r#" b"\W" "#,
    r#" b"\X" "#,
    r#" b"\Y" "#,
    r#" b"\Z" "#,
    r#" b"\[" "#,
    r#" b"\]" "#,
    r#" b"\^" "#,
    r#" b"\_" "#,
    r#" b"\`" "#,
    r#" b"\a" "#,
    r#" b"\b" "#,
    r#" b"\c" "#,
    r#" b"\d" "#,
    r#" b"\e" "#,
    r#" b"\f" "#,
    r#" b"\g" "#,
    r#" b"\h" "#,
    r#" b"\i" "#,
    r#" b"\j" "#,
    r#" b"\k" "#,
    r#" b"\l" "#,
    r#" b"\m" "#,
    r#" b"\o" "#,
    r#" b"\p" "#,
    r#" b"\q" "#,
    r#" b"\s" "#,
    r#" b"\u" "#,
    r#" b"\v" "#,
    r#" b"\w" "#,
    r#" b"\x" "#,
    r#" b"\y" "#,
    r#" b"\z" "#,
    r#" b"\{" "#,
    r#" b"\|" "#,
    r#" b"\}" "#,
    r#" b"\~" "#,


    //// CR checks:

    " '\r'",
    " b'\r'",

    " \"CR \r forbidden\"",
    " b\"CR: \r forbidden\"",
    " c\"CR: \r forbidden\"",

    " r\"CR: \r forbidden\"",
    " br\"CR: \r forbidden\"",
    " cr\"CR: \r forbidden\"",

    " \"CR in string\\\n\n\r\tcontinuation \"",
    " b\"CR in string\\\n\n\r\tcontinuation \"",
    " c\"CR in string\\\n\n\r\tcontinuation \"",

    " r\"not a string\\\n  \r  continuation \" ",
    " br\"not a string\\\n  \r  continuation \" ",
    " cr\"not a string\\\n  \r  continuation \" ",


    //// NUL in C string

    " c\"\0\" ",
    r#" c"\0" "#,
    r#" c"\x00" "#,
    r#" c"\u{0}" "#,
    r#" c"\u{00000}" "#,
    r#" c"\u{0_0_0_0}" "#,
    " cr\"\0\" ",


    //// Integer

    "0 00 123",
    "9876543210",
    "1_2_3_4",
    "1_2_3_4_",
    "123suffix",
    "123f64",
    "123_suffix",
    "123e",
    "123E",
    "123_e",
    "123em",
    "123EM",
    "123em+",
    "123_em",
    "123e_",
    "123e__",
    "340282366920938463463374607431768211456",
    "9999999999999999999999999999999999999999",

    "0b",
    "0b__",
    "0be",
    "0bE",
    "0bem",
    "0b·",
    "0b1·",
    "0be0·",
    "0b101",
    "0b_0_1_0_",
    "0b_0_1_0_suffix",
    "0b19",
    "0b1a",
    "0b1e",
    "0b1em",
    "0_b101",

    "0o",
    "0o__",
    "0oe",
    "0oE",
    "0oem",
    "0o·",
    "0o1·",
    "0oe0·",
    "0o1234567",
    "0o_1_2_3_suffix",
    "0o1234568",
    "0o1234569",
    "0o123a",
    "0o1e",
    "0o1em",

    "0x",
    "0x__",
    "0xa",
    "0xy",
    "0xe",
    "0xem",
    "0x·",
    "0x1·",
    "0xa·",
    "0xe0·",
    "0xabcde",
    "0x_a_b_c_d_e_",
    "0xabcdefg",
    "0xabcdef_g",
    "0xA",
    "0xE",
    "0xABCDE",
    "0x_A_B_C_D_E_",
    "0xABCDEFG",
    "0xABCDEF_G",
    "0xffffffffffffffffffffffffffffffffffffffff",
    "0x01_e3",
    "0x01e3",
    "0x01_E3",
    "0x01E3",
    "0x1e",
    "0x1em",

    "0B0",
    "0O0",
    "0X0",
    "0z0",

    "1️⃣",

    //// Float

    "0.0",
    "123.4",
    "9999999999999999999999999999999999999999.9999999999999999999999999999999999999999",
    "123.40",
    "123.45f32",
    "123.4.5",
    "123.4_5_6_",
    "123.4_",
    "123.4_suff",
    "0x1ffp10",

    "1.",
    "1.f32",
    "1.xxx",
    "1.a",
    "1.e2",
    "1..2",
    "0x1..2",
    r#"1.b"xxx""#,
    r#"1.c"xxx""#,
    r#"1.r"xxx""#,
    r#"1.q"xxx""#,
    r#"1.r#for"#,

    "0e",
    "0e_",
    "0e_1",
    "0_e",
    "123e5",
    "123e5f64",
    "123e5_f64",
    "123e+5",
    "123e-5",
    "123E5",
    "123E+5",
    "123E-5",
    "123e+",
    "123e-",
    "123e_5",
    "123e_5_",
    "123e_suff",
    "123e_suff_",
    "123e+x",
    "123e+_",
    "123e+_x",
    "123e+_5",
    "123e+_56_f64",
    "123e+_+",
    "123e_+56",
    "123e++",

    "123.4e5",
    "123.4e5f64",
    "123.4e5f_64",
    "123.4_5_6_e7",
    "123.4e+5",
    "123.4e-5",
    "123.4E5",
    "123.4_5_6_E7",
    "123.4E+5",
    "123.4E-5",
    "123.4e",
    "123.4e+",
    "123.4e-",
    "123.4e_",
    "123.4e__",
    "123.4e_5",
    "123.4e_5_",
    "123.4e_suff",
    "123.4e+x",
    "123.4e+_",
    "123.4e+_x",
    "123.4e+_5",
    "123.4e+_56_f64",
    "123.4e+_+",
    "123.4e_+56",
    "123.4e++",

    "123.4em",
    "123.4_e",
    "123.4_em",
    "123.4e5em",
    "123.4e5_em",
    "123e4em",
    "123e4_em",
    "123.4em+",
    "123.4E_5",
    "123.4E",
    "123.4EM",
    "123E4EM",

    // See https://github.com/rust-lang/rust/pull/131656
    "123·",
    "123.4·",
    "123e·",
    "123e4·",
    "123_·",
    "123.4_·",
    "123e_·",
    "123e__·",
    "123e4_·",
    "123.4e_·",
    "123.4e5_·",
    "123e4e_·",
    "123.4e5e_·",
    "123e+_·",
    "123.4e+_·",
    "0b1e_·",
    "0b1e__·",
    "0o1e_·",
    "0o1e__·",

    ".0",
    "123e5.6",
    "123._4_5_6_",
    "123._4e5",
    "123._",

    "0b1.0",
    "0o1.2",
    "0x1.2",
    "0xa.2",
    "0x1.a",
    "0x1._",
    "0x1._1",
    "0b1. 0",
    "0o1. 2",
    "0x1. 2",
    "0x1e2",
    "0xAe2",
    "0o1e2",
    "0o9e2",
    "0oAe2",
    "0b1e0",
    "0bAe0",
    "0o1e2",
    "0b1e+",
    "0b1e-",
    "0b1e+1",
    "0b1e-1",
    "0o1e+",
    "0o1e-",
    "0o1e+2",
    "0o1e-2",
    "0x1e+",
    "0x1e-",
    "0x1e+2",
    "0x1e-2",
    "0z3.4",


    // Colour- and UUID-like forms, that macros might use

    "#aabbcc",
    "#aabb11",
    "#112233",
    "#1122aa",
    "#112e33",
    "#112e3a",
    "#11223e",
    "#1122ea",
    "7ad85a2c-f2d0-11fd-afd0-b3104db0cb68",
    "7ad85a2c-f2d0-11ed-afd0-b3104db0cb68",
    "7ad85a2c-f2d0-111e-afd0-b3104db0cb68",


    //// Combinations

    "/* my source file */ fn main() { println!(\"zebra\"); }\n",
    r##"-1+0zzz1 2yyy(3)-[4]+{5}r#foo2!'bar 67"qqq"8'lbl/**/fn"##,
    r##" "string\"one"_suff ident "stringtwo" "##,
    "\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f",


    //// BOM

    "\u{feff}",
    "\u{feff}bom",
    "bom\u{feff}\n\u{feff}bom\n",


    //// CRLF removal

    "one\r\ntwo\r\nthree",
    "one\r\ntwo\rthree",
    " \"one\r\ntwo\r\nthree\" ",
    " \"one\r\ntwo\rthree\" ",
    " r\"one\r\ntwo\r\nthree\" ",
    " r\"one\r\ntwo\rthree\" ",
    " b\"one\r\ntwo\r\nthree\" ",
    " b\"one\r\ntwo\rthree\" ",
    " //!one\r\ntwo\r\nthree ",
    " //!one\r\ntwo\rthree\" ",
    " \"one\r\r\ntwo\" ",
    " r\"one\r\r\ntwo\" ",


    //// Shebang

    "#!/shebang\n",
    "#!/shebang\nfn",
    "#!/shebang\n\n",
    "#!/shebang\nfn",
    "#!/shebang\n£",
    "#!\n",
    "#!\nfn",
    "#!",
    "#!shebang",
    "#!shebang\n",
    "#![attr]\n",
    "#! [attr]\n",
    "#!\n[attr]\n",
    "#! /* nondoc */ [attr]\n",
    "#! // nondoc\n[attr]\n",
    "#! /** doc */ [attr]\n",
    "#! /// doc\n[attr]\n",
    // CRs around shebang
    "#!/shebang\r\n",
    "#!/shebang\r\nfn",
    "#!/shebang\r",
    "#!/shebang\rfn",
    "#!/shebang\rxxx\nfn",
    "#!\r\n",
    "#!\r\nfn",
    "#!\r\n[attr]\n",
    // BOM and shebang
    "\u{feff}#!/shebang\n",
    "\u{feff}#!/shebang\nfn",
    "#!/shebang\n\u{feff}",


    //// Frontmatter

    // Basic good cases
    "---\n---\n",
    "---\nfront matter\n---\n",
    "---\n---\nident",
    "---\nfront matter\n---\nident",
    "----\nfront matter\n----\nident",
    "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\nfront matter\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\nident",
    "---\r\nfront matter\r\n---\r\nident",

    // What follows the frontmatter
    "---\nfront matter\n---\n//! words\n",
    "---\nfront matter\n---\n#![attr]\n",
    "---\nfront matter\n---\n\nident",
    "---\nfront matter\n---\n\n//! words\n",
    "---\nfront matter\n---\n\n#![attr]\n",
    "---\nfront matter\n---\n---",
    "---\nfront matter\n---\n---\nident",
    "---\nfront matter\n---\n---\nsecond front matter\n---\nident",

    // What's inside the front matter
    "---\n\n---\nident",
    "---\nline one\nline two\n---\nident",
    "---\nline one\r\nline two\n---\nident",
    "---\nfront £ matter\n---\nident",
    "---\nfront matter 🦀\n---\nident",
    "---\nfront matter\n--\n---\nident",
    "---\nfront matter\nx---\n---\nident",
    "---\nfront matter\n ---\n---\nident",
    "---\nfront matter\n ----\n---\nident",
    "---\n ---🦀\n---\nident",
    "---\nfront matter\n----\n---\nident",
    "----\nfront matter\n---\n----\nident",
    "-----\nfront matter\n----\n-----\nident",
    "---\nfront matter\nuse x\n---\nident",
    "---\nfront matter\n//! x\n---\nident",
    "---\nfront matter\n#![attr]\n---\nident",

    // Start fence (info strings)
    "--- \nfront matter\n---\nident",
    "--- \t\nfront matter\n---\nident",
    "---infostring\nfront matter\n---\nident",
    "--- infostring\nfront matter\n---\nident",
    "--- \tinfostring\nfront matter\n---\nident",
    "---infostring \nfront matter\n---\nident",
    "---infostring\t \nfront matter\n---\nident",
    "---\u{000C}infostring\u{000C}\nfront matter\n---\nident",
    "---\r \nfront matter\n---\nident",
    "---\rinfostring\nfront matter\n---\nident",
    "---infostring\r \nfront matter\n---\nident",
    "---info_string2\nfront matter\n---\nident",
    "---info·string\nfront matter\n---\nident",
    "---info.string\nfront matter\n---\nident",
    "---info-string\nfront matter\n---\nident",
    "---info+string\nfront matter\n---\nident",
    "---info🧵\nfront matter\n---\nident",
    "---info-\nfront matter\n---\nident",
    "---_infostring\nfront matter\n---\nident",
    "---.infostring\nfront matter\n---\nident",
    "--- -infostring\nfront matter\n---\nident",
    "---2infostring\nfront matter\n---\nident",
    "---·infostring\nfront matter\n---\nident",
    " ---\nfront matter\n---\nident",
    "\t---\nfront matter\n---\nident",
    "\u{000C}---\nfront matter\n---\nident",

    // End fence
    "---\nfront matter\n---tail\nident",
    "---\nfront matter\n--- \nident",
    "---\nfront matter\n---  \nident",
    "---\nfront matter\n---\t\nident",
    "---\nfront matter\n---\u{000C}ident",
    "---\nfront matter\n---\r \nident",
    "----\nfront matter\n---- \nident",
    "---\nfront matter\r---\nident",
    "---\nfront matter\n---\rident",

    // Pairing fences
    "-----\nfront matter\n-----\nident",
    "---\nfront matter\n----\nident",
    "----\nfront matter\n---\nident",
    "---\nfront matter\n ---\nident",
    " ---\nfront matter\n ---\nident",
    "---\n",
    "---\nunterminated\n",
    "---\nfront matter\nuse x\nident",
    "---\nfront matter\n//! x\nident",
    "---\nfront matter\n#![attr]\nident",
    "----\n🦀---\n ---\nident", // #146847
    "---🦀--- ---", // Minimal case of #146847

    // What's before the frontmatter
    "ident\n---\nfront matter\n---\nident",
    "ident---\nfront matter\n---\nident",
    "\n---\nfront matter\n---\nident",
    "\n\n---\nfront matter\n---\nident",
    " \n---\nfront matter\n---\nident",
    " \n \n---\nfront matter\n---\nident",
    "\t\n---\nfront matter\n---\nident",
    "\r---\nfront matter\n---\nident",
    "\r\n---\nfront matter\n---\nident",
    "\r\r\n---\nfront matter\n---\nident",
    "\u{000C}\n---\nfront matter\n---\nident",
    "\n ---\nfront matter\n---\nident",

    // BOM and shebang
    "#!/shebang\n---\nfront matter\n---\nident",
    "#!/shebang\r\n---\r\nfront matter\r\n---\r\nident",
    "#!/shebang\n\n---\nfront matter\n---\nident",
    "#!\n---\nfront matter\n---\n[]",
    "\u{feff}---\nfront matter\n---\n[]",
    "---\nfront matter\n---\n#!/notshebang\n",

    // No newline at EOF
    "---",
    "---\n---",
    "---\n--- ",


    //// Delimiters

    "a ( [ { ((b)) } (c) {} ] ) d",
    "unclosed ( paren",
    "close brace } first",
    "unclosed ( [ bracket in group )",
    "mismatched { delimiters )",

]
.as_slice();

/// These tests fail in at least some models.
pub const XFAIL: &[&str] = [
    // This doesn't work in decl-compare: it breaks out of the macro invocation.
    ");}; const _: () = { (",
]
.as_slice();
