#!/bin/sh
set -e
cd $(dirname $0)/..

SRC=src/lex_via_peg/pretokenisation/pretokenise.pest
ANCHORED=writeup/pretokenise_anchored.pest
CLEANED=writeup/pretokenise.pest

sed \
    -e 's!PUSH(HASHES)!HASHES¹!' \
    -e 's!PEEK!HASHES²!' \
    -e 's!POP!HASHES²!' \
    < $SRC > $ANCHORED

sed -e '\!^//!d' < $SRC > $CLEANED


SRC=src/frontmatter.pest
SIMPLIFIED=writeup/frontmatter_simplified.pest
UNCHANGED=writeup/frontmatter.pest

sed \
    -e 's!PUSH(FENCE)!FENCE¹!' \
    -e 's!PEEK!FENCE²!' \
    -e 's!POP!FENCE²!' \
    < $SRC > $SIMPLIFIED

cp $SRC $UNCHANGED
