#!/bin/sh
set -e
cd $(dirname $0)/..

SRC=src/lex_via_peg/tokenise.pest
ANCHORED=writeup/tokenise_anchored.pest
CLEANED=writeup/tokenise.pest

sed \
    -e 's!PUSH(HASHES)!HASHES¹!' \
    -e 's!PEEK!HASHES²!' \
    -e 's!POP!HASHES²!' \
    < $SRC > $ANCHORED

sed -e '\!^//!d' < $SRC > $CLEANED


SRC=src/reimplementation/cleaning/frontmatter.pest
ANCHORED=writeup/frontmatter_anchored.pest
CLEANED=writeup/frontmatter.pest

sed \
    -e 's!PUSH(FENCE)!FENCE¹!' \
    -e 's!PEEK!FENCE²!' \
    -e 's!POP!FENCE²!' \
    < $SRC > $ANCHORED

sed -e '\!^//!d' < $SRC > $CLEANED
